repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
      - id: clang-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        types_or: [c, c++]
      - id: end-of-file-fixer
        types_or: [c, c++]
      - id: check-merge-conflict
      - id: mixed-line-ending
        types_or: [c, c++]
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs
        exclude: \.mk$|Makefile|Kconfig|\.gitmodules
      - id: remove-tabs
        exclude: \.mk$|Makefile|Kconfig|\.gitmodules
        args:
          - --whitespaces-count
          - "4"
      - id: chmod
        args: ["644"]
        files: \.md$
      - id: insert-license
        types_or: [c, c++]
        args:
          - --license-filepath
          - license_header.txt
          - --comment-style
          - //
          - --use-current-year
